"""update user relationship

Revision ID: 32645abd8a58
Revises: 520aff94ac19
Create Date: 2022-01-25 17:43:20.497325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32645abd8a58'
down_revision = '520aff94ac19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transactions', 'transactions', ['offset_transactions_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    # ### end Alembic commands ###
