"""update models

Revision ID: 33d13485d33b
Revises: 1ff68f765c15
Create Date: 2023-01-04 08:16:16.882606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d13485d33b'
down_revision = '1ff68f765c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transactions_offset_transactions_id_fkey', 'transactions', 'transactions', ['offset_transactions_id'], ['id'], use_alter=True)
    op.add_column('transactions_scheduled', sa.Column('offset_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions_scheduled', 'accounts', ['offset_account_id'], ['id'])
    op.drop_column('transactions_scheduled', 'interval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions_scheduled', sa.Column('interval', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions_scheduled', type_='foreignkey')
    op.drop_column('transactions_scheduled', 'offset_account_id')
    op.drop_constraint('transactions_offset_transactions_id_fkey', 'transactions', type_='foreignkey')
    # ### end Alembic commands ###
