"""add is_active to scheduled transactions

Revision ID: 3d95cdfbdd44
Revises: b8097c295e4a
Create Date: 2024-06-23 09:14:17.818896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d95cdfbdd44'
down_revision: Union[str, None] = 'b8097c295e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions_scheduled', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions_scheduled', 'is_active')
    # ### end Alembic commands ###
