"""cascade on delete

Revision ID: 544b25e4c6f6
Revises: f0e07e937a46
Create Date: 2024-02-25 20:03:08.021766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544b25e4c6f6'
down_revision: Union[str, None] = 'f0e07e937a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_account_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('transactions_scheduled_account_id_fkey', 'transactions_scheduled', type_='foreignkey')
    op.create_foreign_key(None, 'transactions_scheduled', 'accounts', ['account_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions_scheduled', type_='foreignkey')
    op.create_foreign_key('transactions_scheduled_account_id_fkey', 'transactions_scheduled', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_account_id_fkey', 'transactions', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
