"""fixed use_alter

Revision ID: 75a677d750b4
Revises: 3ca97199de77
Create Date: 2022-01-23 07:38:36.960756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a677d750b4'
down_revision = '3ca97199de77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
