"""added is_income to TransactionSubcategory table

Revision ID: 7af3394f4c3b
Revises: c9de12976d24
Create Date: 2022-02-03 05:55:34.964301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af3394f4c3b'
down_revision = 'c9de12976d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transactions_offset_transactions_id_fkey', 'transactions', 'transactions', ['offset_transactions_id'], ['id'], use_alter=True)
    op.add_column('transactions_subcategories', sa.Column('is_income', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions_subcategories', 'is_income')
    op.drop_constraint('transactions_offset_transactions_id_fkey', 'transactions', type_='foreignkey')
    # ### end Alembic commands ###
