"""remove frequency once from database

Revision ID: 9694a1dffec2
Revises: dbce8a11ecc2
Create Date: 2024-08-19 06:33:39.007768

"""

from typing import Sequence, Union

from alembic import op
from app.models import Frequency

# revision identifiers, used by Alembic.
revision: str = "9694a1dffec2"
down_revision: Union[str, None] = "dbce8a11ecc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f" DELETE FROM {Frequency.__tablename__} WHERE label = 'once'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
