"""update transaction model

Revision ID: b8097c295e4a
Revises: ebc9a4757806
Create Date: 2024-05-20 17:41:41.567122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8097c295e4a'
down_revision: Union[str, None] = 'ebc9a4757806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('scheduled_transaction_id', sa.Integer(), nullable=True))
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'information_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_scheduled_transaction_date', 'transactions', ['scheduled_transaction_id', 'information_id'])
    op.create_foreign_key(None, 'transactions', 'transactions_scheduled', ['scheduled_transaction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint('uq_scheduled_transaction_date', 'transactions', type_='unique')
    op.alter_column('transactions', 'information_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transactions', 'scheduled_transaction_id')
    # ### end Alembic commands ###
