"""add user displayname

Revision ID: f0e07e937a46
Revises: 4885a032ce2e
Create Date: 2023-05-18 14:19:27.748340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e07e937a46'
down_revision = '4885a032ce2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transactions_offset_transactions_id_fkey', 'transactions', 'transactions', ['offset_transactions_id'], ['id'], use_alter=True)
    op.add_column('user', sa.Column('displayname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'displayname')
    op.drop_constraint('transactions_offset_transactions_id_fkey', 'transactions', type_='foreignkey')
    # ### end Alembic commands ###
